name: Trein vertrektijden ophalen

on:
  schedule:
    # Draait van ma t/m vr om de 5 minuten tussen 08:00 en 17:00 NL tijd (06:00-15:00 UTC)
    - cron: "*/5 6-15 * * 1-5"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Repository ophalen
        uses: actions/checkout@v5

      - name: Treingegevens ophalen van NS API (25 ritten)
        env:
          NS_API_KEY: ${{ secrets.NS_API_KEY }}
        run: |
          curl -s -H "Ocp-Apim-Subscription-Key: $NS_API_KEY" \
          "https://gateway.api.ns.nl/reisinformatie-api/api/v2/departures?station=ZL&maxJourneys=25" \
          -o trein.json

      - name: trein.json opslaan
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add trein.json
          git commit -m "Update trein vertrektijden" || echo "Geen wijzigingen"
          git push
